server:
  port: 8083

spring:
  application:
    name: person-api
  r2dbc:
    url: r2dbc:mysql://localhost:3306/user
    username: root
    password: admin123
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql